ahoyapi: v2
commands:
  identify:
    cmd: "python _config.py identify $1"
    usage: Identify extractors for path ($1). Can be file or directory.
  
  identify-smart:
    cmd: "python _config-smart.py extract $1"
    usage: Identify extractors for path ($1) using smart importers. Can be file or directory.

  extract:
    cmd: "python _config.py extract -e my.beancount $1"
    usage: Extract new transactions from path ($1) relative to existing beancount file my.beancount

  extract-smart:
    cmd: "python _config-smart.py extract -e my.beancount $1"
    usage: Extract new transactions from path ($1) using smart importers relative to existing beancount file my.beancount

  archive:
    cmd: "python config.py archive $1 -o archive"
    usage: Archive the input file ($1) to archive/